### ISSUE TITLE
[Unknown] {txblob} isn't in return url for native app after signing "Signin" payload.

### ISSUE THREAD

**Issue by dangell7** [XRPL-Labs/Xaman-Issue-Tracker#365]
**Describe the bug**

The txblob is not returning in the signin request return url. I only use the app return url.

**To Reproduce**

1. Create Signin Payload with app return url.

`app: "https://gambitdev.page.link?payloadID={id}&blobID={txblob}"`

2. Open Xumm App through universal

```
let url = URL(string: "https://\(XRPLHost.xrpl_ws_Xumm.rawValue)/sign/\(payloadID)")
UIApplication.shared.open(url!) { (result) in
    return
}
```

3. Sign and click redirect link
4. In dashboard and app return url is 

`https://gambitdev.page.link/?payloadID=3a5f681c-e267-4b21-8dab-f6696c83404a&blobID={txblob}`

**Expected behavior**

I expected to get the txblob and payload to verify the user.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 2.2

What device are you running XUMM on?

* Manufacturer: Apple
* Model: 11
* OS version: 15
* Platforms
  * [x ] iOS
  * [ ] Android

**Comment by WietseWind** [comment]
Thank you for this report!

I'll dive in and fix this asap.

**Comment by WietseWind** [comment]
@N3TC4T So here's what's happening:
- When the app fetches the payload, the payload info already contains the app return URL (if present):
```
{
  "meta": {
    "exists": true,
    "uuid": "e35fe5dd-8a1b-44d5-a8be-b82b38b5ef88",
    "return_url_app": "https://wietse.com/xrpl?payloadID=e35fe5dd-8a1b-44d5-a8be-b82b38b5ef88&blobID="
}
```

The `return_url_app` is already pre-parsed with all the right params replaced. However, at this stage (when opening the payload) not all params are known yet, so they are being replaced with an empty string. This means the `txid` and `txblob` will be empty, as they are only known *after* the payload has been signed, and the `PATCH` has been sent by XUMM (app) to the backend.

As the URL is fully pre-parsed and vars replaced by the backend, what needs to happen here is this:

- [x] If the original payload does have a `return_url_app`, the app will, after signing, display a `Next` button instead of a `Close` button (already the case)
- [ ] If the payload is signed, and the Next button will be displayed (because there is an `return_url_app`, **AFTER** the `PATCH` with the payload results, the payload must be `GET`ted again, as now the complete `return_url_app` will be returned by the backend. That's the URL the `Next` button must trigger.

**Comment by dangell7** [comment]
I agree, using payloadID to fetch the data is safer than assuming a universal link URL parameters are trustworthy.
